# Generated by Django 6.0.3 on 2026-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeltaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50, unique=True)),
                ("price", models.FloatField()),
                ("assets_m", models.FloatField(default=0.0, verbose_name="总资产(M)")),
                ("hafu_w", models.FloatField(default=0.0, verbose_name="哈夫币(W)")),
                ("show_title", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GenshinAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(max_length=50, unique=True, verbose_name="商品ID"),
                ),
                ("price", models.FloatField(verbose_name="价格")),
                ("level", models.IntegerField(default=0, verbose_name="等级")),
                ("assets_score", models.FloatField(default=0.0, verbose_name="资产分")),
                ("show_title", models.TextField(verbose_name="商品标题")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="抓取时间"),
                ),
            ],
        ),
    ]
